# Site settings
title: Effective Projects
description: > # this means to ignore newlines until "baseurl:"
  Effective Programming Projects
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://projects.effectiveprogramming.com/" # the base hostname & protocol for your site
twitter_username: effprog
github_username:  EffectiveProgramming

permalink: /:year/:month/:day/:title.html

# Build settings
markdown: kramdown

# User added
excludes: go.sh
